name: Publish RunTrackerOverlay

on:
  push:
    branches: [ "master", "main" ] # Adjust to your main branch name
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Publish
      run: dotnet publish RunTrackerOverlay/RunTrackerOverlay.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:ReadyToRun=true -o ./publish

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: RunTrackerOverlay-Windows
        path: ./publish